export const RECORDING_DURATION_MS = 30_000;
export const OFFSCREEN_DOCUMENT_PATH = "offscreen.html";
export const OFFSCREEN_DOCUMENT_REASONS = [
    "USER_MEDIA",
    "AUDIO_PLAYBACK",
    "WORKERS"
];

export const CAPTURE_STATUS = {
    INITIALIZING: "initializing",
    CAPTURING: "capturing",
    CANCELING: "canceling",
    INFERRING: "inferring"
};

export const MESSAGE_TYPE = {
    START_CAPTURE: "OFFSCREEN_START_CAPTURE",
    CANCEL_CAPTURE: "OFFSCREEN_CANCEL_CAPTURE",
    STATE_CHANGED: "CAPTURE_STATE_CHANGED",
    DETECTION_COMPLETED: "DETECTION_COMPLETED",
    DETECTION_FAILED: "DETECTION_FAILED",
    CAPTURE_FINISHED: "CAPTURE_FINISHED"
};
